name: workflow with a trigger
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3
      - name: Run a basic command
        run: echo "Hello, Github Actions!"
